/**
 * Generated by tsnapi — public API snapshot of `@dbarjs/brazilian`
 */
// #region Types
export type CheckSums = [number, number];
// #endregion

// #region Functions
export declare function formatToCEP(_: string): string;
export declare function formatToCNPJ(_: string): string;
export declare function formatToCPF(_: string): string;
export declare function formatToCPFOrCNPJ(_: string): string;
export declare function generateCheckSums(_: Array<number>, _: Array<number>): CheckSums;
export declare function getRemaining(_: number): number;
export declare function isCEP(_: string): boolean;
export declare function isCNPJ(_: string): boolean;
export declare function isCPF(_: string): boolean;
export declare function isCPFOrCNPJ(_: string): boolean;
export declare function isRepeatedArray<T>(_: Array<T>): boolean;
export declare function mapToAlphaNumeric(_: string): string;
export declare function mapToNumbers(_: string): number[];
export declare function mapToNumeric(_: string): string;
export declare function parseCNPJ(_: string): string | undefined;
// #endregion

// #region Variables
export declare const CNPJ_PATTERN: RegExp;
export declare const CPF_PATTERN: RegExp;
// #endregion